module CDC
  module Concurrent
    # Processes TransactionEnvelope events as a single ordering-preserving unit.
    class TransactionPool
      @processor_pool: ProcessorPool

      # @param processor [CDC::Core::Processor]
      # @param concurrency [Integer]
      # @param timeout [Float, nil]
      # @param preserve_order [Boolean]
      def initialize: (processor: processor, ?concurrency: ::Integer, ?timeout: ::Float?, ?preserve_order: bool) -> void

      # @param transaction [CDC::Core::TransactionEnvelope]
      # @return [CDC::Core::ProcessorResult]
      def process: (transaction_envelope transaction) -> processor_result

      # @return [void]
      def shutdown: () -> void
    end
  end
end
